### ISSUE TITLE
【要望】Elevatedも対応して欲しい

### ISSUE THREAD

**Issue by kumability** [rei-suzuki/figma-dark-mode-switcher#1]
Hello!!🐻

普段はUIを設計していて、Dark ModeとDark themaが大好きなくまです。
トクバイのアプリを日頃使っていてお得にお買い物させてもらってます。✌️🐻

今回、Dark Mode SwitcherでDark Modeの対応がしきれてないない
Elevatedをできれば対応して欲しいので要望としてissueを出します。

## 現状の認識
今回のプラグインでは、1つの色に対してDark Modeの状態を無視して1つの色が入れ替わる仕様だと認識して要望させてください。

## 要望と解説
Dark ModeではBaseとElevatedの二つの色の状態が存在します。主にpageSheetにElevatedのカラーが動的にかかると思われます。Light Modeの状態であれば、Modal Viewの状態でも白の色が変わることはありませんが、Dark Modeの場合はsystemBackgroundだったとしてもBaseとElevatedで色が異なるので一対一ではなく一対多でスイッチできる事が理想だと考えます。

現状でもDark ModeのBaseのスイッチとは別にLightでもElevated用に定義することで現状のスペックでも対応することはできますが、定義するカラーが二倍になるだけで大変苦労されると思うので代替手段だとしても管理側のデザイナー的には避けたいです。

また、iOS13の最新のHuman Interface GuidelinesではDark Modeの際に下記引用ようにコントラスト比について述べられています。

>**Ensure that your content remains comfortably legible in Dark Mode when you adjust the contrast and transparency accessibility settings.** 
In Dark Mode, you should test your content with Increase Contrast and Reduce Transparency turned on, both separately and together. You may find places where dark text is less legible when it’s on a dark background. You might also find that turning on Increase Contrast in Dark Mode can result in reduced visual contrast between dark text and a dark background. Although people with strong vision might still be able to read lower contrast text, such text could be illegible for people with visual impairments. For guidance, see [Color and Contrast.](https://developer.apple.com/design/human-interface-guidelines/accessibility/overview/color-and-contrast/)

引用元 : https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/dark-mode/

Elevatedは濃淡が全体的に薄くなります。デザイナーが意図せずコントラスト比が確保されないケースを作ってしまわないように本番環境とほぼ同じようにDark Modeが確認できることをお願いしたいです。これらを対応することでユーザーはコントラスト比が4.5:1を確保した状態で多くの人が見易いアプリを利用できるメリットがあります。😉

一対多の定義は難しいかと思われますが、検討のほどよろしくお願いします。🐻

**Comment by ar-tama** [comment]
@kuma0520 

こんにちは！ co-maintainerの @ar-tama です。お返事が遅くなり失礼しました。（トクバイのご利用ありがとうございます！嬉しいです 😊 ）
リクエストありがとうございます。現在 #10 で対応していますが、後方互換性を考えて一対多ではなく Dark, Elevated, Light の三種類のキーワードに対応させることにしました。
そのため `Dark/Base/Primary` `Dark/Elevated/Primary` といった名付けをされている場合は、このプラグインではサポート対象外となってしまいます 🙇 🙏 
よろしければPRもご覧いただき、気になる点がありましたらぜひコメントをください 😉
