### ISSUE TITLE
Strokes do not change to Light or Dark when toggling

### ISSUE THREAD

**Issue by peiman** [rei-suzuki/figma-dark-mode-switcher#2]
Hi! 
Thanks for a great plugin.

I was applying dark mode styles and discovered that strokes that use Dark and Light color styles don't convert when toggling.

Could you look into it?

**Comment by rei-suzuki** [comment]
@peiman Hi! Thank you for drafting the issue. Sorry for the delay in responding. 
The stroke response is complete. The latest version is now available on Figma. Please keep using it!
