### ISSUE TITLE
Could not get the plugin to work

### ISSUE THREAD

**Issue by rrhyne** [rei-suzuki/figma-dark-mode-switcher#3]
Hi Rei, great idea for a plugin!

I could not get it to work in my files. Here is the file I had an issue with:

https://www.figma.com/file/3hm11Po89mewQFokfct0Up/RRMMColors?node-id=3%3A1

I believe I have set it up properly, but when I select light or dark mode, nothing changes. 

I've sent your support email address edit capabilities on the file.

**Comment by rei-suzuki** [comment]
@rrhyne Hi! Thanks for asking.
You need to register a color for `Light` in Local Styles.
Looking at the Figma file, there are two `Background/Dark/Primary`, but isn't one of them `Background/Light/Primary`?

**Comment by rrhyne** [comment]
You were correct, my naming was not right. Thanks so much!
