### ISSUE TITLE
External color styles

### ISSUE THREAD

**Issue by orlanmarty** [rei-suzuki/figma-dark-mode-switcher#5]
Hi Rei 👋,

Thank you for creating and sharing this plugin. I was trying to make the switch from light to dark mode with external color styles but noticed that it only works with local colors.

For example, I'd like to keep all the colors in a Design System file, implement it to individual files and use the plugin within those.

Is there a way to do this? If not, is it in the roadmap to implement this? 

Thanks! ✌️

**Comment by rei-suzuki** [comment]
@orlanmarty Hi! Thank you for asking.
Sorry for the late reply.

When I had it verified at hand, the Design System color was also changed. Can you tell us a little more about what the condition is?

**Comment by rei-suzuki** [comment]
Sorry, I was wrong and the plugin did not work in DesignSystem. I'll see if I can do it.

**Comment by peiman** [comment]
@rei-suzuki I have the same wish! I also want to tell you that the plugin is AWESOME! Thanks for creating it!

**Comment by hzlzh** [comment]
only works for local style? wish support external styles

**Comment by mdias-zai** [comment]
Hi @rei-suzuki !! Amazing plugin 😄 
Would also love to see it working with color libraries
Thank you!!

**Comment by ar-tama** [comment]
@orlanmarty @peiman @hzlzh @monikeoreilly-cf 

Hi I'm @ar-tama,  co-maintainer for the plugin.
Thank you for waiting! We just merged the Team Library(DesignSystem) supported feature. However we have trouble publishing as a production on [install page](https://www.figma.com/community/plugin/808916768872750785/Dark-Mode-Switcher). We're going to announce agin after publish.
You can use the feature by clone, build and run as development mode when you want to get ASAP. [Setup Guide](https://www.figma.com/plugin-docs/setup/) may help you. Also, README says usage. Please check it out:)

**Comment by rei-suzuki** [comment]
@orlanmarty @peiman @hzlzh @monikeoreilly-cf 
We have successfully released the plugin. Thanks for your patience. I hope you will continue to use it. Thank you!

https://www.figma.com/community/plugin/808916768872750785/Dark-Mode-Switcher
